class LCDocs {
  static Map<String, Map<String, String>> indDocs = {
    "How to Give Constructive Feedback on Writing": {
      "Introduction":
          "Providing constructive feedback on someone\'s writing is a task more difficult than it seems, requiring balance, clarity, and empathy. Writers often pour personal effort and creativity into their work, so feedback can feel deeply personal. Research in writing instruction and pedagogy offers strategies to ensure that feedback is both helpful and encouraging, fostering improvement while maintaining the writer\'s motivation.",
      "Start with the Strengths":
          "According to studies on feedback by researchers at the University of Cambridge, beginning with positive comments builds trust and boosts the writer's confidence. Acknowledge what is working well before diving into areas for improvement. This could be anything from strong arguments and clear structure to engaging voice or creativity in description. For example, \"Your introduction really grabs the reader\'s attention,\" or \"I love how vivid your imagery is in the second paragraph.\"",
      "Be Specific, Not Vague":
          "General comments like \"This needs more detail\" or \"This isn\'t clear\" are less helpful than specific feedback. Research from the National Writing Project highlights the importance of targeted, precise comments that guide the writer toward improvement. Instead of saying, \"The argument is weak,\" try, \"In this section, your argument would be stronger with more evidence. Could you add an example or a quote to back up this claim?\"",
      "Prioritize Key Areas":
          "Overloading a writer with too many critiques at once can be overwhelming. Research from the Writing Center at UNC Chapel Hill suggests focusing on two or three major issues at a time, such as organization, clarity, or evidence. Addressing smaller, surface-level concerns like grammar or word choice can come later. For example, \"Your overall argument is solid, but the transitions between your paragraphs feel abrupt. Let\'s work on making those smoother.\"",
      "Use Questions to Encourage Reflection":
          "Feedback should feel collaborative, not authoritarian. According to a study from the University of Toronto, asking questions invites the writer to engage critically with their own work, leading to more meaningful revisions. For example, instead of saying, \"Your conclusion is weak,\" ask, \"How do you want the reader to feel after finishing your piece? Is there a way to reinforce that in your conclusion?\"",
      "Balance Critique with Suggestions for Improvement":
          "While pointing out weaknesses is necessary, offering practical suggestions for improvement is equally important. According to research from the University of Michigan\'s Writing Program, feedback that includes actionable steps fosters motivation and clarity. For example, instead of simply stating, \"This sentence is unclear,\" you could say, \"Rephrasing this sentence to focus on the main point might help, how about \"The policy change led to significant improvements in local education systems\'?\"",
      "Encourage the Writer's Voice and Intentions":
          "Writers often worry that too much feedback will erase their voice or original intent. Research published in College Composition and Communication highlights the importance of validating the writer\'s unique style while helping them refine it. Frame your feedback in a way that respects their creative choices. For example, \"I see you\'re aiming for a conversational tone here, which works well for engaging the reader. However, you might want to tighten this section for clarity without losing that friendly tone.\"",
      "Focus on Revision as a Process":
          "Writing is an iterative process, and feedback should encourage ongoing improvement rather than instant perfection. Research from The Writing Teacher\'s Sourcebook recommends promoting the idea of writing as a draft-revise-edit cycle. Instead of viewing feedback as criticism, frame it as a tool for refinement. For example, \"This draft has great potential! In the next revision, you could strengthen the argument by including more supporting examples.\"",
    },
    "How to Get Over Writer\'s Block": {
      "Introduction":
          "Writer\'s block is something all writers face, whether you\'re crafting bestselling novels or just starting out with a personal journal. It occurs when the flow of ideas stalls, leading to frustration and sometimes even abandonment of projects. While it\'s tempting to wait for inspiration to strike, research suggests that writer\'s block is more about mindset and writing habits than a lack of creativity. Fortunately, there are strategies to overcome it, many of which focus on breaking through mental barriers and fostering a productive writing routine.",
      "Stop Editing, Just Write":
          "One of the primary reasons for writer\'s block is the tendency to edit while writing. According to research from the University of Toronto, writers who try to perfect their sentences as they go often lose momentum, becoming overly focused on small details at the expense of progress. Psychologist Mihaly Csikszentmihalyi, who coined the term flow to describe the mental state of full immersion in an activity, argues that writers need to push through the first draft without worrying about quality. The key is to allow ideas to come out freely without censoring or revising them.Instead of pausing to tweak every sentence, try \"free writing\": a technique where you write continuously for a set period without stopping to edit. This approach helps you get your thoughts onto the page, leaving refinement for later stages of the process. As writer Anne Lamott famously said, \"Almost all good writing begins with terrible first efforts.\"",
      "Flush Out Your Ideas Without Worrying About Organization":
          "Another effective way to break through writer\'s block is to flush out all of your ideas, regardless of organization or structure. Research from Stanford University\'s Writing and Rhetoric Department shows that perfectionism and the desire for order often stifle creativity, leading to a paralysis of ideas. Instead, jot down your thoughts as they come, without worrying about how they fit together yet. This brainstorming phase should be messy, embracing incomplete thoughts, fragments, or even random associations.This process of dumping ideas without immediate structure aligns with the concept of cognitive load theory, which suggests that our brains can only process a limited amount of information at once. By writing down everything in a loose, chaotic manner, you free up cognitive space, allowing your mind to focus on generating more ideas rather than sorting them prematurely.",
      "Create an Outline from Your Ideas":
          "Once you've flushed out your ideas, creating an outline can bring clarity and direction to your writing. Research published by the Journal of Writing Research found that writers who use outlines are more productive and less likely to experience writer\'s block. Outlining allows you to organize the scattered ideas from your brainstorming phase into a logical structure. It provides a roadmap for your writing, making it easier to see how the pieces fit together and where gaps need to be filled.Outlining also aligns with goal setting theory, which posits that setting clear goals improves performance. By breaking down your writing into smaller, manageable sections with an outline, you create achievable milestones that make the task feel less overwhelming. For example, if you're working on an essay, your outline might break the work into an introduction, main arguments, supporting evidence, and a conclusion. Having this framework in place can help you stay on track and maintain momentum.",
      "Change Your Environment or Routine":
          "Research from The American Psychological Association shows that sometimes a change in environment can stimulate creativity. If you\'re stuck in a creative rut, consider writing in a different location, such as a cafe, park, or library. According to a study published in The Journal of Environmental Psychology, new surroundings can activate different parts of the brain, fostering creativity and new perspectives.Additionally, changing your writing routine can help break the cycle of writer\'s block. If you typically write at the same time each day, try experimenting with different times or writing in shorter bursts. Incorporating activities like free writing, mind mapping, or even taking breaks to do unrelated tasks can re-energize your mind.",
      "Embrace the Writing Process as Iterative":
          "Many writers feel blocked because they expect their first draft to be perfect, leading to pressure and anxiety. However, research emphasizes that writing is an iterative process. Professor Donald M. Murray\'s research on writing instruction highlights that writing involves drafting, revising, and rewriting. Embracing this process allows you to see writing as something that evolves over time. The initial draft is only a starting point, and it\'s normal for it to be rough or incompleteIncorporating this mindset means accepting that you may need to return to your writing several times, refining ideas and improving structure with each pass. Instead of seeing this as a failure, view it as an opportunity to explore different angles and sharpen your work.",
    },
    "How to Begin Brainstroming a Narrative": {
      "Introduction":
          "Writing a narrative is a personal journey, and each writer\'s process is unique. There\'s no single \"right\" way to begin; what works for one person may not work for another. The following strategies are suggestions designed to help you explore your creativity, find what feels natural, and build a structure that supports your storytelling. Feel free to adapt these techniques in ways that best suit your style.",
      "Start with a Central Theme or Question":
          "Research in narrative theory highlights the value of grounding your story in a central theme or question to provide focus. This might be as broad as \"How does fear influence decision-making?\" or as specific as \"What happens when a friendship is tested by betrayal?\" This focus serves as an anchor, giving your narrative a sense of direction. However, how you choose to explore this theme is up to you; some writers prefer to brainstorm multiple themes before settling on one, while others may develop it naturally as the story progresses.",
      "Freewrite to Unlock Creativity":
          "Freewriting is a technique supported by studies from the University of California Berkeley, which show that it can enhance creativity by bypassing the internal editor. Set a timer for 10-15 minutes and write continuously without worrying about coherence or structure. This practice allows ideas to emerge freely, capturing the raw and unfiltered material that may become the core of your story. Adapt this method to fit your style; some writers prefer shorter or longer sessions, while others might incorporate music or other stimuli to stimulate inspiration.",
      "Embrace the Messiness of Idea Generation":
          "Research on cognitive load theory suggests that offloading unorganized ideas helps free up mental capacity for further creativity. In this phase, jot down everything that comes to mind, whether it\'s fragments of scenes, character details, or sensory impressions. The goal is not to organize yet but to let your imagination flow. Whether you use a journal, digital notes, or even sketch out visual elements, allow this stage to be as unstructured as possible; your approach can be as visual, written, or spontaneous as you prefer.",
      "Create an Outline":
          "Outlining is a method backed by research published in the Journal of Writing Research, which suggests that writers who outline often feel less overwhelmed. However, outlining should be flexible and suit your style. You can structure your narrative loosely, mapping out major events, or create a detailed roadmap with specific scenes and character arcs. If outlining feels restrictive, try alternative methods like mind mapping or storyboarding. Adapting the outline to fit your needs ensures it enhances, rather than limits, your creativity.",
      "Develop Characters Based on Your Approach":
          "Character development is central to compelling storytelling. Research shows that well-rounded characters deepen reader engagement, but the process of creating them can vary. Some writers prefer starting with detailed character profiles, considering motivations, backgrounds, and emotional arcs. Others might discover characters through dialogue or by placing them in different scenarios. Experiment with methods like \"interviewing\" your characters or writing flashbacks to explore their depth, adapting the approach that resonates most with your style.",
      "Experiment with Settings and Perspectives":
          "According to studies in The Journal of Creative Process Studies, exploring diverse settings and perspectives can stimulate new ideas. Experiment with different time periods, locations, or points of view to see how they alter the tone or direction of your narrative. You might find it useful to visualize settings with sketches or mood boards, or you might prefer describing them vividly through freewriting. This stage is about playing with possibilities, letting you see which elements enhance the story most effectively."
    }
  };
}
